name: Send Threat Feed to FortiGate

on:
  push:
    paths:
      - feed.txt  # Trigger workflow only when feed.txt changes

jobs:
  send-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read feed.txt and format as JSON array
        id: prepare
        run: |
          entries=$(jq -R . feed.txt | jq -cs .)
          echo "ENTRIES_JSON<<EOF" >> $GITHUB_ENV
          echo "$entries" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send feed to FortiGate
        run: |
          echo "Sending feed.txt to FortiGate..."

          curl -k -X POST \
            -H "Authorization: Bearer ${{ secrets.FGT_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{
              "commands": [
                {
                  "name": "Test1",
                  "command": "add",
                  "entries": '"$ENTRIES_JSON"'
                }
              ]
            }' \
            "https://83.174.140.148:8443/api/v2/monitor/system/external-resource/dynamic?vdom=TSIND"
