name: Update FortiGate External Feed

on:
  push:
    paths:
      - 'feed.json'

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send Feed to FortiGate
        run: |
          curl -k -X POST \
          -H "Authorization: Bearer ${{ secrets.FGT_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data "@feed.json" \
          "${{ secrets.FGT_API_URL }}"
